### PR TITLE
added POST XML action card

### PR DESCRIPTION
**Pull request by RobertoPeters**

### CODE REVIEW

**Comment by RobertoPeters** [comment]
Once the XML has been entered, it works.
However there are two issues (probably caused by one thing)
1. you cannot paste an xml into the data
2. rebooting removes the XML tag
Probably due to the format. If you don't want to perform this pull request, then please advise me where I need to change this.

**Comment by irritanterik** [comment]
Thank you for your contribution!
Can you extend `readme.md` with this card and bump version number in `package.json`?
And will use of json to xml converion resolve both issues? The xml2js package allready used with this app supports bi-directional conversions:

```
var builder = new xml2js.Builder();
var xml = builder.buildObject(obj);
```

If not, please request athom to support 'plain text' input fields on flow cards.

**Comment by RobertoPeters** [comment]
I updated the readme and app version, but somehow I cannot do a new pull request.
But actually, you decide what the new version number would need to be.
And as for the xml2js builder. Actually, I just want text and not xml. Most cards have this, but I just don't get it how its done. I hope you can do this.

**Comment by irritanterik** [comment]
I added support for POST XML with commit 5109ab0 . Reboot keeps the typed XML now. I will push this to the app store in a few days.

**Comment by irritanterik** [comment]
Thanks for your contribution!

**Pull request closed without merging**
